version: '3'

services:
  consul-agent-1:
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    # Complete copy of 'consul-agent-1'
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-3:
    # Complete copy of 'consul-agent-1'
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-1:
    # Uses only image and networks from 'consul-agent-1'
    # while 'command' is overwritten
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    # Complete copy of 'consul-server-1'
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    # Uses only image and networks from 'consul-agent-1'
    # while 'command' is overwritten and 'ports' are defined
    image: consul:latest
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8501:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  gateway:
    image: kirillesau/spring-gateway-showcase
    ports:
      - "8888:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-server-bootstrap
    networks:
      - consul-demo

  demo-service:
    image: kirillesau/spring-demo-application
    deploy:
      replicas: 3
    environment:
      - spring.cloud.consul.host=consul-server-bootstrap
    networks:
      - consul-demo

networks:
  consul-demo: