version: '3.9'

services:

  consul-server:
    image: hashicorp/consul:1.15.2
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
      - ./consul/kv-store:/consul/config/kv-store
      - consul:/consul/data
    networks:
      - consul-demo
    ports:
      - "8501:8500"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.15.2
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - consul-demo
    command: "agent"

  gateway:
    image: kirillesau/spring-gateway-showcase
    depends_on:
      - consul-server
    ports:
      - "8888:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-server
    networks:
      - consul-demo

  spring-demo-application:
    image: kirillesau/spring-demo-application
    depends_on:
      - consul-client
      - consul-server
      - spring-demo-db
    deploy:
      replicas: 3
    environment:
      - spring.cloud.consul.host=consul-server
      - spring.datasource.url=jdbc:postgresql://spring-demo-db:5432/postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.username=postgres
      - spring.datasource.password=mypw123
      - spring.jpa.hibernate.ddl-auto=update
      - spring.sql.init.mode=always
    networks:
      - consul-demo
      - spring-demo

  spring-demo-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mypw123
    networks:
      - spring-demo

networks:
  consul-demo:
  spring-demo:
volumes:
  consul: